### PR TITLE
Added buffs: Earth Shield, Power Word: Fortitude

### PR DESCRIPTION
**Pull request by Attict**
Hey Phanx,

I ended up re-implementing my changes from scratch to clean everything up.  I still have my old changes as well, incase I am missing anything, but it sounds like my changes have been implemented in a better way.

I can't test anything until tonight, but here are at least the buff additions.  I'm still not completely sure where you want "missing = true" (guessing in the general buff info), but feel free to add it in.   If any of my changes are still necessary, I will implement them as soon as I have a better idea what is needed!

### CODE REVIEW

**Comment by rherzfeld** [comment]
I think he meant Power Word: Fortitude and it should look like this:
```
[GridStatusAuras:StatusForSpell("Power Word: Fortitude", true)] = {
		-- 21562
		desc = format(L["Buff: %s"], spell_names["Power Word: Fortitude"]),
		buff = spell_names["Power Word: Fortitude"],
		text = GridStatusAuras:TextForSpell(spell_names["Power Word: Fortitude"]),
		color = { r = 0, g = 0.7, b = 0.3, a = 1 },
		missing = true,
	},
```

**Comment by Attict** [comment]
That's kind of what I thought, but wanted to make sure before adding it, since I didn't see any other buffs with that attribute.  Added the 'missing' property for Power Word: Fortitude.

**Comment by Attict** [comment]
Tested these changes last night, looks good from what I noticed!

**Comment by Phanx** [comment]
Looks good. That's exactly what I meant about the `missing` option; there weren't any default buffs with that option set because there weren't (for some years now) any long-duration raid buffs that anyone needed to be concerned with keeping up.

Re: Soothing Mist -- Normally I would say no to a status for the target of a spell you have to channel to maintain, but since you can cast other spells on the same target while you're channeling this one, and you could have click-cast it on a target other than your actual target, I'm okay with it in this case.

Merging.

**Pull request merged**
