### PR TITLE
BfA pre-patch fix

### PR DESCRIPTION
**Pull request by arbi316**
I've made pre-patch fix

modified codes related to aura scan for optimizing

### CODE REVIEW

**Comment by Attict** [comment]
Hi Arbi,  thanks for taking the time to fix these changes! 👍  It looks like all of the BFA changes are fixed on the bfa branch, but not pushed into the master branch.  I've also added a couple of spells (Power Word: Fortitude and Earth Shield) beyond these changes if you need them, they are on my version.  Also, I believe the Libs are meant to be ignored since they are populated on install from the sources.

**Comment by arbi316** [comment]
Thanks for your response. I just wished @Phanx will merge my changes and push his own master branch. Redeemed raid buffs better not added because they have long duration (30min ~ 1hour) and push away other short and important buffs on Grid.

Libs, yeah. They're unnecessary things for developers but I forked this branch for normal users. They will not use this without libs. I'll link my branch on Curseforge reply for many normal users

**Comment by doadin** [comment]
there are way too many useless commits in this to be even considered. theres ~45 commits with names "Create .gitignore" and "Delete .gitignore" at the very least these should be combined.(rebase -i, squish) however they appear to be mostly from the libs being included which if anything I think the best solution if libs where to be included they should be added as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). To which for most libs you would have to create a new repository for each as a lot are hosted in svn not git. not being the owner of this repo this is my opinion which Phanx may or maynot agree with any or all of it.

**Comment by rherzfeld** [comment]
I agree with @doadin, the .gitignore was setup to ignore the /Lib folder for a reason. They do not belong into the source.

**Comment by Phanx** [comment]
There are too many duplicate/irrelevant commits in this PR to be mergeable. If there are any actual code changes that aren't already covered in #6 please get them on a clean branch and open a new PR.

Also, libraries should **_not_** be included in the Grid repository. Libraries are pulled at build time by the release script.

**Pull request closed without merging**
