### PR TITLE
Merged BFA branch into master, added new buff types, and fixed other issues

### PR DESCRIPTION
**Pull request by Attict**
I have tested these changes, and all is working great.

Also, I have the LibResInfo-1.0 files here (Also needed UnitAura changes), with notes of how to use in the README: https://github.com/Attict/Grid-Extra

Finally, I want to say great work with Grid.  I've used it since BC, and loved it as a healer.  If you need someone to pass this off to for maintaining, I will gladly take this on as a project.  I am not very familiar with working on WoW addons, but I do work as a developer, so this should be no problem to pick up!  If so, and there is any advice/help you could provide, I will gladly accept it.  Thanks Phanx!

### CODE REVIEW

**Comment by Lorune** [comment]
Perhaps you can take a look at this one, it happens on brewmaster monks.

```
Message: Interface\AddOns\Grid\Statuses\Stagger.lua:172: Usage: UnitDebuff("unit", [index][, "filter"])
Time: Thu Jul 19 21:56:27 2018
Count: 1
Stack: Interface\AddOns\Grid\Statuses\Stagger.lua:172: Usage: UnitDebuff("unit", [index][, "filter"])
(tail call): ?
[C]: in function `UnitDebuff'
Interface\AddOns\Grid\Statuses\Stagger.lua:172: in function `?'
...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ings\lib\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```

Your other changes in the commit work fine, i just checked them out, and no issues anymore on any characters i have access to besides the brewmaster monk.

**Comment by Attict** [comment]
I will fix it as soon as I can, no later than tonight.  Other have mentioned that debuffs are not working properly.  Also, power word: fortitude was not working, which should be fixed now (untested if anyone can confirm).

**Comment by Attict** [comment]
@Lorune This should be fixed, but again is untested.

**Comment by bkarpati** [comment]
I have been using this fork on my holy paladin for the last couple of days. Everything seems to be working fine. I didn't get any LUA errors either.

**Comment by Phanx** [comment]
Looks good, though since you changed the line endings in the Auras module, the diff covers 100% of the file, making it impossible to see what actually changed in there. Can you restore the original line ending style?

**Comment by rherzfeld** [comment]
@Phanx At the top of the comparison you can change diff settings to hide whitespace changes. You can then see the actual changes.

**Comment by Phanx** [comment]
Ah okay, wasn't aware GitHub had that feature. Thanks for pointing it out.

The actual changes look good, but I don't want to merge all those irrelevant whitespace changes. Not only did the line endings get changed, but some tabs got changed to spaces, large chunks of the file got an extra level of indentation, virtually every comment block gained or lost indentation for no apparent reason, etc. There's even one point where a whole function got shifted up above the final `end` statement of the previous function; it's not breaking anything because it's a method on the module object, but it is definitely incorrect. (This may even be the cause of most of the other problems; if your IDE does a lot of automatic whitespace "correction" it may have tried to compensate for the new nested structure.)

A few other technical issues with the PR:

- There are a bunch of commits adding and removing `print` statements. You generally don't want to actually commit these temporary debugging changes into version control, and I definitely don't want them in the main repository. The easiest way to get rid of them at this point is probably an interactive rebase and liberal use of fixup/squash or just dropping the whole commit.

- There is some unrelated refactoring in the Resurrect module that makes it hard to see what actually changed. I'm not opposed to the refactoring itself, but I'd prefer to keep that separate from actual code changes.

- When adding new auras, please insert them into the list in proper alphabetical order. This helps future maintenance by making it easy to see at a glance whether a specific aura is included.

@Attict If you want to do some rebasing to clean up the PR (depending on how GitHub feels about `--force` you may have to open a new PR after rebasing) I'm happy to merge it; otherwise I can just cherry-pick your commits where it's possible and copy/paste your changes where it's not. Either way, the time you've put into updating and testing is much appreciated.

**Comment by Phanx** [comment]
Also just an FYI the LibResInfo library lives in its own repository, here:
https://github.com/phanx-wow/LibResInfo

The UnitAura changes were already made there, and as of earlier tonight I tagged a stable version that includes those changes. I haven't really been able to test them, though; if you've encountered problems that needed additional changes to fix, you can open a PR on the library repo.

**Comment by Attict** [comment]
@Phanx Glad to hear from you! I can't agree more with some of your points.  I fixed the spell order, and tab indention.   I've also rebased most of my commits.  I don't believe I should have any changes in resurrect and stagger, I'll take a look in a bit to see if I can figure out where these are coming from.

**Comment by Phanx** [comment]
Thanks. `Auras.lua` is still showing 1738 lines added and 1712 lines removed though, which tells me there's still a lot of whitespace discrepancies.

The easiest way to fix it is probably going to be rename your current file (e.g. `Auras.lua.new`), drop in a copy of `Auras.lua` from the current `master`, then manually copy over _just_ the actual changes you can see in a "don't show the whitespace" diff. (As rherzfield helpfully pointed out above, GitHub has that feature now, see https://github.com/phanx-wow/Grid/pull/6/files?utf8=%E2%9C%93&diff=unified&w=1)

On second glance, I'm actually not quite sure what's supposed to be going on in the block at the end of the diff you've labelled with the "temporary test solution" comment. It looks like you're trying to fix the "show only mine" option; if that's the case then #10 which I merged last night should already cover that, so you can just remove this part (that'll also fix the merge conflict).

You should also do another pass through `git rebase -i` and `reword` fecbec5; it looks like in your first rebase you did a squash to get rid of those debug commits (good) but forgot to delete their commit messages, so if you view the full commit message for that one resulting commit, it's still got all the lines in there about adding and removing debug messages.

Finally, for long-duration buffs like Power Word: Shield, the default settings should include `missing = true` to only show the indicator if the buff is missing. Otherwise you end up with an extra indicator shown on every raid frame, which is counter to the "show the least amount of stuff necessary" spirit of Grid.

**Pull request closed without merging**
