### PR TITLE
Fix: Buff status with "Show as mine" again only showing when cast by …

### PR DESCRIPTION
**Pull request by rherzfeld**
…player

### CODE REVIEW

**Comment by rherzfeld** [comment]
I can now see, that this is also fixed by #6, though that requires more calls to UnitAura.

It would also be possible to use the isCastByPlayer return value from UnitAura:
`name, icon, count, debuffType, duration, expirationTime, caster, isStealable, _, _, _, _, isCastByPlayer = UnitAura(unit, i, "HELPFUL")`

**Comment by Phanx** [comment]
Yes, I'd prefer to use `isCastByPlayer` over manually comparing `caster == "player"`. If you want to make that change I'll happily merge this.

I haven't gotten to review all of #6 yet (specifically, I haven't looked at the Auras module changes at all in that PR because Git's diff is unusable due to line ending changes) but if there's any conflict I can deal with that later, and I'd rather use whatever solution is (a) requires the least code and (b) requires the fewest number of function calls.

**Comment by rherzfeld** [comment]
Apparently `isCastByPlayer` doesn't work right now. Just tested with a guild mate and it always returned true. Got the documentation from [here](https://wow.gamepedia.com/API_UnitAura) and thought it would work.
So, no further changes.

**Comment by Phanx** [comment]
Oh, Blizzard. :roll_eyes: 

Merging. Thanks!

**Pull request merged**
